[package]
name = "hfuzz"
version = "0.1.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5.49"
fuzz_targets = { path = "../fuzz_targets", default-features = false }

[workspace]